//
//  AppAuthError.swift
//  EditorPhoto
//
//  Created by Ильфат Салахов on 14.05.2024.
//

import Foundation

enum AppAuthError: Error {
    case invalidCustomToken
    case customTokenMismatch
    case invalidCredential
    case userDisabled
    case operationNotAllowed
    case emailAlreadyInUse
    case invalidEmail
    case wrongPassword
    case tooManyRequests
    case userNotFound
    case accountExistsWithDifferentCredential
    case requiresRecentLogin
    case providerAlreadyLinked
    case noSuchProvider
    case invalidUserToken
    case networkError
    case userTokenExpired
    case invalidAPIKey
    case userMismatch
    case credentialAlreadyInUse
    case weakPassword
    case appNotAuthorized
    case expiredActionCode
    case invalidActionCode
    case invalidMessagePayload
    case invalidSender
    case invalidRecipientEmail
    case missingEmail
    case missingIosBundleID
    case missingAndroidPackageName
    case unauthorizedDomain
    case invalidContinueURI
    case missingContinueURI
    case missingPhoneNumber
    case invalidPhoneNumber
    case missingVerificationCode
    case invalidVerificationCode
    case missingVerificationID
    case invalidVerificationID
    case missingAppCredential
    case invalidAppCredential
    case sessionExpired
    case quotaExceeded
    case missingAppToken
    case notificationNotForwarded
    case appNotVerified
    case captchaCheckFailed
    case webContextAlreadyPresented
    case webContextCancelled
    case appVerificationUserInteractionFailure
    case invalidClientID
    case webNetworkRequestFailed
    case webInternalError
    case webSignInUserInteractionFailure
    case localPlayerNotAuthenticated
    case nullUser
    case dynamicLinkNotActivated
    case invalidProviderID
    case tenantIDMismatch
    case unsupportedTenantOperation
    case invalidDynamicLinkDomain
    case rejectedCredential
    case gameKitNotLinked
    case secondFactorRequired
    case missingMultiFactorSession
    case missingMultiFactorInfo
    case invalidMultiFactorSession
    case multiFactorInfoNotFound
    case adminRestrictedOperation
    case unverifiedEmail
    case secondFactorAlreadyEnrolled
    case maximumSecondFactorCountExceeded
    case unsupportedFirstFactor
    case emailChangeNeedsVerification
    case missingClientIdentifier
    case missingOrInvalidNonce
    case blockingCloudFunctionError
    case invalidPassword
    case passwordDoNotMatch
    
    var localizedDescription: String {
        switch self {
        case .invalidCustomToken:
            return "invalidCustomToken".localized
        case .customTokenMismatch:
            return "customTokenMismatch".localized
        case .invalidCredential:
            return "invalidCredential".localized
        case .userDisabled:
            return "userDisabled".localized
        case .operationNotAllowed:
            return "operationNotAllowed".localized
        case .emailAlreadyInUse:
            return "emailAlreadyInUse".localized
        case .invalidEmail:
            return "invalidEmail".localized
        case .wrongPassword:
            return "wrongPassword".localized
        case .tooManyRequests:
            return "tooManyRequests".localized
        case .userNotFound:
            return "userNotFound".localized
        case .accountExistsWithDifferentCredential:
            return "accountExistsWithDifferentCredential".localized
        case .requiresRecentLogin:
            return "requiresRecentLogin".localized
        case .providerAlreadyLinked:
            return "providerAlreadyLinked".localized
        case .noSuchProvider:
            return "noSuchProvider".localized
        case .invalidUserToken:
            return "invalidUserToken".localized
        case .networkError:
            return "networkError".localized
        case .userTokenExpired:
            return "userTokenExpired".localized
        case .invalidAPIKey:
            return "invalidAPIKey".localized
        case .userMismatch:
            return "userMismatch".localized
        case .credentialAlreadyInUse:
            return "credentialAlreadyInUse".localized
        case .weakPassword:
            return "weakPassword".localized
        case .appNotAuthorized:
            return "appNotAuthorized".localized
        case .expiredActionCode:
            return "expiredActionCode".localized
        case .invalidActionCode:
            return "invalidActionCode".localized
        case .invalidMessagePayload:
            return "invalidMessagePayload".localized
        case .invalidSender:
            return "invalidSender".localized
        case .invalidRecipientEmail:
            return "invalidRecipientEmail".localized
        case .missingEmail:
            return "missingEmail".localized
        case .missingIosBundleID:
            return "missingIosBundleID".localized
        case .missingAndroidPackageName:
            return "missingAndroidPackageName".localized
        case .unauthorizedDomain:
            return "unauthorizedDomain".localized
        case .invalidContinueURI:
            return "invalidContinueURI".localized
        case .missingContinueURI:
            return "missingContinueURI".localized
        case .missingPhoneNumber:
            return "missingPhoneNumber".localized
        case .invalidPhoneNumber:
            return "invalidPhoneNumber".localized
        case .missingVerificationCode:
            return "missingVerificationCode".localized
        case .invalidVerificationCode:
            return "invalidVerificationCode".localized
        case .missingVerificationID:
            return "missingVerificationID".localized
        case .invalidVerificationID:
            return "invalidVerificationID".localized
        case .missingAppCredential:
            return "missingAppCredential".localized
        case .invalidAppCredential:
            return "invalidAppCredential".localized
        case .sessionExpired:
            return "sessionExpired".localized
        case .quotaExceeded:
            return "quotaExceeded".localized
        case .missingAppToken:
            return "missingAppToken".localized
        case .notificationNotForwarded:
            return "notificationNotForwarded".localized
        case .appNotVerified:
            return "appNotVerified".localized
        case .captchaCheckFailed:
            return "captchaCheckFailed".localized
        case .webContextAlreadyPresented:
            return "webContextAlreadyPresented".localized
        case .webContextCancelled:
            return "webContextCancelled".localized
        case .appVerificationUserInteractionFailure:
            return "appVerificationUserInteractionFailure".localized
        case .invalidClientID:
            return "invalidClientID".localized
        case .webNetworkRequestFailed:
            return "webNetworkRequestFailed".localized
        case .webInternalError:
            return "webInternalError".localized
        case .webSignInUserInteractionFailure:
            return "webSignInUserInteractionFailure".localized
        case .localPlayerNotAuthenticated:
            return "localPlayerNotAuthenticated".localized
        case .nullUser:
            return "nullUser".localized
        case .dynamicLinkNotActivated:
            return "dynamicLinkNotActivated".localized
        case .invalidProviderID:
            return "invalidProviderID".localized
        case .tenantIDMismatch:
            return "tenantIDMismatch".localized
        case .unsupportedTenantOperation:
            return "unsupportedTenantOperation".localized
        case .invalidDynamicLinkDomain:
            return "invalidDynamicLinkDomain".localized
        case .rejectedCredential:
            return "rejectedCredential".localized
        case .gameKitNotLinked:
            return "gameKitNotLinked".localized
        case .secondFactorRequired:
            return "secondFactorRequired".localized
        case .missingMultiFactorSession:
            return "missingMultiFactorSession".localized
        case .missingMultiFactorInfo:
            return "missingMultiFactorInfo".localized
        case .invalidMultiFactorSession:
            return "invalidMultiFactorSession".localized
        case .multiFactorInfoNotFound:
            return "multiFactorInfoNotFound".localized
        case .adminRestrictedOperation:
            return "adminRestrictedOperation".localized
        case .unverifiedEmail:
            return "unverifiedEmail".localized
        case .secondFactorAlreadyEnrolled:
            return "secondFactorAlreadyEnrolled".localized
        case .maximumSecondFactorCountExceeded:
            return "maximumSecondFactorCountExceeded".localized
        case .unsupportedFirstFactor:
            return "unsupportedFirstFactor".localized
        case .emailChangeNeedsVerification:
            return "emailChangeNeedsVerification".localized
        case .missingClientIdentifier:
            return "missingClientIdentifier".localized
        case .missingOrInvalidNonce:
            return "missingOrInvalidNonce".localized
        case .blockingCloudFunctionError:
            return "blockingCloudFunctionError".localized
        case .invalidPassword:
            return "invalidPassword".localized
        case .passwordDoNotMatch:
            return "passwordDoNotMatch".localized
        }
    }
}
